require("rileymathews.remap")
require("rileymathews.lazy")
require("rileymathews.telescopesetup")
require("rileymathews.treesittersetup")
require("rileymathews.lspsetup")
require("rileymathews.theme")
vim.cmd('set relativenumber')
vim.cmd('set number')
