require("rileymathews.set")
require("rileymathews.lazy")
require("rileymathews.telescopesetup")
require("rileymathews.treesittersetup")
require("rileymathews.lspsetup")
require("rileymathews.theme")
require("rileymathews.remap")
